import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "WikiRocket!",
  description: "Generated by Wicki",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-l from-gray-400 to-gray-300">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
